server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liga7_equipos
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database: mysql
    generate-ddl: true
