server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/edhydev/java-microservicios
          search-paths: config-data
  application:
    name: server-config
